[package]
name = "flocking_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.16"
kiddo = "0.2.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
